# Generated by Django 2.2.7 on 2019-12-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_product',
            new_name='comments_product',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_text',
            new_name='comments_text',
        ),
    ]
